### ISSUE TITLE
Install instructions for mac

### ISSUE THREAD

**Issue by sindrig** [sindrig/spoppy#142]
Add instructions for mac installation to README.md

**Comment by Neverbolt** [comment]
I'd like to do that

**Comment by sindrig** [comment]
I'd love that. Don't have a mac so I'm not sure what help I can bring, but let me know if you get stuck along the way and I'll try to help you. 

A PR to README.rst would be great!

**Comment by Neverbolt** [comment]
Will do!

**Comment by Neverbolt** [comment]
Okay, so I checked it out and it seems (at least to me) that the line
`pyalsaaudio>=0.8.2`
is not needed.
Also it is the line that is currently breaking MacOS support, since there is no alsaaudio for MacOS.
However, if I take it out I can just build and use it as usual, the tests run with ok as well.
Is there any use for pyalsaaudio that I'm missing?

**Comment by sindrig** [comment]
I'm out of the country until Tuesday so I'm afraid I won't be any help until then, but I'm really excited about this.

**Comment by sindrig** [comment]
Okay first thing I can think of is that ALSA sinks might be hard to use on Mac OS X. In pyspotify they've also implemented PortAudioSink (https://github.com/mopidy/pyspotify/blob/v2.x/develop/spotify/sink.py) which requires [PortAudio](http://www.portaudio.com/) and [PyAudio](https://pypi.python.org/pypi/pyaudio). We might have to dynamically populate the requirements in setup.py to include pyaudio and then select that sink in lifecycle.py instead of the AlsaSink. How does that sound?

**Comment by Neverbolt** [comment]
I've already got a working model for that, gonna push it in the next hours or so.
